@startuml

cloud "Интернет канал" as external
component "FIREWALL" as fw

package "DMZ" {
    component "Интернет портал" as portal
    component "Дилерский портал" as dealer
    component "СКУД" as skud
    database "MySQL портала" as portal_db
    database "Postgres СКУДА" as skud_db
    component "Антивирус" as av
}

package "Access-зона" {
    component "VPN" as vpn
    component "Terminal Service Gateway" as ts
    component "Jump-сервер" as jump
}

package "Application-сегмент" {
    component "CRM" as crm
    component "ИС Кадры" as staff
    component "ИС Бухгалтерия" as accounting
    component "ИС Юридическая" as legist
    component "Телефония" as tele
    component "Дисковое хранилище" as storage
    node "MSSQL сервер" as db_server {
        database "БД Бухгалтерии" as accounting_db
        database "БД кадров" as staff_db
        database "БД антивируса" as av_db
        database "БД почты" as mail_db
        database "MySQL CRM" as crm_db
    }
}

package "Mechanics-сегмент" {
    component "Система диагностики авто" as diagnostic
    component "Система коллерной" as coller
    component "рабочие станции слесарей" as mech_pc
}

package "AD" {
    component "Active Directory" as ad
    component "Почта" as mail
}

package "Finance" {
    component "Банк-клиент" as bc
    database "SQLITE" as bc_db
}

package "Users" {
    component "рабочие станции бухгалтерии" as acc_pc
    component "ноутбуки менеджеров" as mgr_pc
}

package "mgmt" {
    component "Рабочая станция администратора" as admin_pc
    component "Терминальный сервер" as term_server
}

component "Принтеры" as print

external --> fw
fw --> portal
fw --> dealer
fw --> skud
fw --> vpn
fw --> ts

portal --> portal_db
skud --> skud_db
av --> av_db

vpn --> jump
ts --> jump
jump --> admin_pc
jump --> acc_pc

crm --> crm_db
accounting --> accounting_db
staff --> staff_db
mail --> mail_db
storage --> crm

acc_pc --> accounting
acc_pc --> crm
acc_pc --> bc
mgr_pc --> crm
mech_pc --> diagnostic
mech_pc --> coller

acc_pc ..> ad
mgr_pc ..> ad
mech_pc ..> ad
admin_pc ..> ad

acc_pc -- print
mech_pc -- print
tele -- acc_pc

admin_pc --> term_server

@enduml
